### ISSUE TITLE
Css Zoom

### ISSUE THREAD

**Issue by ransombot** [paulirish/css3please#59]
I don't think that zooming is in the official specs it would make a good addition since it's doable.

``` css
 .box_zoom {
    zoom: 1.5; /* IE */
    -moz-transform: scale(1.5); /* Firefox */
    -webkit-transform: scale(1.5); /* Safari & probably Chrome */
}
```

Code from: http://stackoverflow.com/questions/2026294/zoom-css-javascript/2026384#2026384
